### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by manuvariego** [manuvariego/League-Inform#2]
- [x] Investigate the usage of webhooks and discords "Heartbeats & Gateways" , define if the project should use a library or if it's better to build it utilizing the former.
- [ ] Create more tests to facilitate debugging
- [ ] Establish a scope on the actions that the bot will carry out 
- [ ] Integrate the usage of the 'ctx' & 'sync' libraries to speed up requests between the bot and the RIOT API
- [x] Use waitgroups and mutexes to run concurrent goroutines, (prevent data races!!)
